### ISSUE TITLE
请问如何获取多个串口? COM4,COM5这种.能知道串口号.

### ISSUE THREAD

**Issue by mimimiaomiao1** [itldg/web-serial-debug#1]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/58240619/209523814-a110275c-5853-4695-aa29-17090ec61eb4.png">

图里的这个方法,只能获取当前的串口,但是不知道COM多少.

**Comment by itldg** [comment]
这个我没有成功,我记得在哪个文档上看的说名字和端口可能会泄露计算机隐私,所以没开放,现在我也找不到出处了

**Comment by mimimiaomiao1** [comment]
> 

哎..我是用blazor,我想用blazor来实现一些基础的窗体程序功能. 就需要同事连接多个串口,但是需要串口号对应..

**Comment by itldg** [comment]
你的多个串口,设备驱动一样么

**Comment by mimimiaomiao1** [comment]
> 

设备驱动都一样的,一样的牌子. 然后设备管理器能看到串口号不一样,COM4,COM5,COM6..

**Comment by itldg** [comment]
那就不好办了,如果productId之类的不同,可以代码自己区分
目前的情况前端不好区分了,chrome有计划给每个串口都分配唯一id,但是目前应该还没实现

https://github.com/WICG/serial/issues/128

**Comment by mimimiaomiao1** [comment]
> 那就不好办了,如果productId之类的不同,可以代码自己区分 目前的情况前端不好区分了,chrome有计划给每个串口都分配唯一id,但是目前应该还没实现
> 
> [WICG/serial#128](https://github.com/WICG/serial/issues/128)

那可以这样么,迂回战术,比如,我插上了五个串口,能否获取到这五个串口的VID和PID, 因为VID和PID是固定的..能获取到这个信息也是可以的.

**Comment by itldg** [comment]
可以`port.getInfo()`

但是你应该会获取到五个相同的

**Comment by mimimiaomiao1** [comment]
> 可以`port.getInfo()`
> 
> 但是你应该会获取到五个相同的

能方便发一下联系方式吗? Q    
我不确定我写的是否正确,我没有在getInfo下找到有用的内容

**Comment by itldg** [comment]
已我的代码为例
serialPort.getInfo()
{usbProductId: 19968, usbVendorId: 6018}

**Comment by mimimiaomiao1** [comment]
> 

<img width="428" alt="image" src="https://user-images.githubusercontent.com/58240619/209529854-6ff7e90c-586a-4f58-94fb-63faa3666458.png">
我不知道pid,vid是多少.我想知道应该用什么方法来获取

**Comment by itldg** [comment]
navigator.serial.requestPort().then(async (port) => {
  console.log(port.getInfo())
})

我是这样做

**Comment by mimimiaomiao1** [comment]
> 

<img width="378" alt="image" src="https://user-images.githubusercontent.com/58240619/209592285-f1e659ea-78a5-420c-b3ab-a6b4bb8ed22e.png">
我选择了两个不同的串口,但是信息确实一样的...

**Comment by itldg** [comment]
意料之中,这个帖子我关闭了,有问题再开新贴反馈吧
