### ISSUE TITLE
串口信息被解析为html

### ISSUE THREAD

**Issue by lhcdwz** [itldg/web-serial-debug#2]
当串口通信里面的信息内容符合html规范时，内容被浏览器解析了，没办法看到原始内容了
![捕获](https://github.com/itldg/web-serial-debug/assets/81622189/98e991dd-57ba-4c70-b8a5-e3a4f4bcca8d)

**Comment by itldg** [comment]
好的，问题收到，有时间我来看看

**Comment by itldg** [comment]
推送了一个版本,试试看这个问题是否已解决

**Comment by lhcdwz** [comment]
> 推送了一个版本,试试看这个问题是否已解决

可以的，完美解决
