### ISSUE TITLE
串口消息过长导致界面异常

### ISSUE THREAD

**Issue by xiaowine** [itldg/web-serial-debug#4]
一条串口消息过长会导致左边部分的界面往后面推，界面变成一个滚动，需要往右边滑动才能点击到
希望加一个串口过长时自动换行功能

**Comment by itldg** [comment]
麻烦附一个异常的截图，有时间的话就来处理这个问题

**Comment by xiaowine** [comment]
> 麻烦附一个异常的截图，有时间的话就来处理这个问题

貌似最近的一个pr修复了这个问题，我继续使用几天，没问题后我会自行关闭issues

**Comment by itldg** [comment]
> > 麻烦附一个异常的截图，有时间的话就来处理这个问题
> 
> 貌似最近的一个pr修复了这个问题，我继续使用几天，没问题后我会自行关闭issues

好的，感谢这么晚了还在反馈。也很高兴这个项目能帮助到你

**Comment by itldg** [comment]
如果没有问题的话这个issues要关闭了
