### ISSUE TITLE
Dynamic Serial Port Parameter Adjustment Requirement: Modifying Baud Rate, Data Bits, and Parity Bit Without Closing the Port

### ISSUE THREAD

**Issue by dzyqj** [itldg/web-serial-debug#5]
老.王 Mr. Wang, your project is excellent, but could you possibly modify parameters such as baud rate, data bits, and parity bit without closing the serial port while it is open? It's too cumbersome to close the serial port every time we need to modify the parameters. Could you address this issue? Thank you very much!

**Comment by itldg** [comment]
Ok, the suggestion is received. I will try to improve this problem in subsequent versions. I'm glad this project is helpful to you.

**Comment by itldg** [comment]
I didn't find an API that can modify the parameters without closing the serial port, I made a little optimization, if the parameters change automatically reopen the serial port, you see how the experience is
