### ISSUE TITLE
您好，您是如何做到重新打开浏览器不用再次选择串口的呢？

### ISSUE THREAD

**Issue by jbnjvc10000** [itldg/web-serial-debug#8]
您好，我在看您写的浏览器串口调试工具，想请教下:
web serial api 好像不支持指定串口的com口，或者指定串口的设备id？
但是我用您的网页的时候，重新打开浏览器，却不用再次指定串口，这是为什么呢？是浏览器缓存吗？

**Comment by itldg** [comment]
1. 是的,无法指定串口
2. 页面加载时会先获取已经取得权限的串口,https://github.com/itldg/web-serial-debug/blob/c0fc58b9fe9f197f1b660e207c2af237c4cbdc47/js/common.js#L6-L11
